plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    id 'com.chaquo.python'
}

android {
    namespace 'com.harsh.deepsolver'
    compileSdk 36

    defaultConfig {
        applicationId "com.harsh.deepsolver"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }

        python {
            buildPython "python"
            pip {
                install "requests"
                install "beautifulsoup4"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.10.0')
    implementation 'com.google.firebase:firebase-analytics'

    // Chaquopy dependency
    implementation 'com.chaquo.python:gradle:15.0.1'

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
